import { NextRequest } from "next/server";
import { auth } from "@/auth";
import { getAuthUserId } from "@/lib/api/handlers";
import { checkRateLimit } from "@/lib/rateLimit";
import { getRepo, getLatestAnalysis, getLatestSdkPrRequest } from "@/lib/db/queries";
import { createSdkPrRequest, updateSdkPrRequest } from "@/lib/db/jobs";
import { GitHubPrCreator } from "@/lib/github/pr-creator";
import { buildPrFileChanges } from "@/lib/sdk-pr/transformer";
import type { LLMCallSite } from "@/lib/sdk-pr/transformer";

const PR_BODY = `## Verum SDK Integration

This PR was automatically generated by [Verum](https://verum-production.up.railway.app) to integrate the Verum Loop into your AI service.

### What's included

- \`src/lib/verum/client.ts\` — inline Verum SDK client (no npm install required)
- \`.env.example\` — Verum environment variable templates
- \`// TODO: [Verum]\` comments on every detected LLM call site showing where to integrate

### Next steps

1. Set \`VERUM_API_URL\`, \`VERUM_API_KEY\`, and \`VERUM_DEPLOYMENT_ID\` in your environment
2. Follow each \`TODO: [Verum]\` comment to wrap the call with \`VerumClient\`
3. Verum will then A/B test your prompts automatically

> Not affiliated with Verum AI Platform (verumai.com).
`;

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await auth();
  const user = session?.user as Record<string, unknown> | undefined;
  const userId = user?.id as string | undefined;
  if (!userId) return new Response("unauthorized", { status: 401 });
  const rateLimitResponse = checkRateLimit(userId, 20);
  if (rateLimitResponse) return rateLimitResponse;
  const accessToken = user?.github_access_token as string | undefined;
  if (!accessToken) return new Response("github_access_token missing from session", { status: 401 });

  const { id: repoId } = await params;

  const repo = await getRepo(userId, repoId);
  if (!repo) return new Response("repo not found", { status: 404 });

  const analysis = await getLatestAnalysis(repoId);
  if (!analysis) return new Response("no analysis found for this repo", { status: 404 });
  if (analysis.status !== "done") return new Response("analysis not complete yet", { status: 409 });

  const callSites = (analysis.call_sites ?? []) as LLMCallSite[];
  const repoFullName = repo.github_url.replace("https://github.com/", "");

  const creator = new GitHubPrCreator({ accessToken, repoFullName });

  const filesToRead = [".env.example", ...callSites.map((s) => s.file_path)];
  const existingFiles: Record<string, string> = {};
  await Promise.all(
    filesToRead.map(async (path) => {
      const content = await creator.readFile(path);
      if (content !== null) existingFiles[path] = content;
    }),
  );

  const fileChanges = buildPrFileChanges({ callSites, existingFiles, repoFullName });
  const branchName = `verum/sdk-integration-${Date.now()}`;
  const requestId = await createSdkPrRequest({ userId, repoId, analysisId: analysis.id });

  try {
    const { pr_url, pr_number } = await creator.createPr({
      branchName,
      baseBranch: repo.default_branch,
      title: "Add Verum SDK integration",
      body: PR_BODY,
      files: fileChanges,
    });

    await updateSdkPrRequest(requestId, {
      status: "pr_created",
      pr_url,
      pr_number,
      branch_name: branchName,
      files_changed: fileChanges.length,
    });

    return Response.json(
      { request_id: requestId, pr_url, pr_number, files_changed: fileChanges.length },
      { status: 201 },
    );
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    await updateSdkPrRequest(requestId, { status: "error", error });
    return Response.json({ error }, { status: 502 });
  }
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const userId = await getAuthUserId();
  if (!userId) return new Response("unauthorized", { status: 401 });
  const { id: repoId } = await params;
  const request = await getLatestSdkPrRequest(userId, repoId);
  if (!request) return new Response("not found", { status: 404 });
  return Response.json(request);
}
