import { NextRequest } from "next/server";
import { z } from "zod";
import { auth } from "@/auth";
import { getAuthUserId } from "@/lib/api/handlers";
import { checkRateLimit } from "@/lib/rateLimit";
import { getRepo, getLatestAnalysis, getLatestInference, getLatestSdkPrRequest } from "@/lib/db/queries";
import { createSdkPrRequest, updateSdkPrRequest } from "@/lib/db/jobs";
import { GitHubPrCreator } from "@/lib/github/pr-creator";
import { buildPrFileChanges } from "@/lib/sdk-pr/transformer";
import type { PrMode } from "@/lib/sdk-pr/transformer";

const LLMCallSiteSchema = z.object({
  file_path: z.string().min(1),
  line: z.number().int().nonnegative(),
  sdk: z.string(),
  function: z.string(),
  prompt_ref: z.string().nullable(),
});

const CallSitesSchema = z.array(LLMCallSiteSchema);

const PR_BODY_OBSERVE = `## Verum Observability (Phase 0)

This PR was automatically generated by [Verum](https://verum-production.up.railway.app) to add zero-code observability to your AI service.

### What's included

- \`.env.example\` — OTLP and Verum environment variable templates

### Next steps

1. Set the env vars shown in \`.env.example\` in your deployment environment
2. Install the instrumentation library:
   - Python: \`pip install 'verum[instrument]'\` then \`import verum.openai\` at startup
   - Node.js: \`npm install @verum/sdk\` then \`import "@verum/sdk/openai"\` at startup
3. Verum will begin collecting traces automatically

> Not affiliated with Verum AI Platform (verumai.com).
`;

const PR_BODY_BIDIRECTIONAL = `## Verum SDK Integration (Phase 1)

This PR was automatically generated by [Verum](https://verum-production.up.railway.app) to integrate the Verum auto-instrument SDK into your AI service.

### What's included

- \`.env.example\` — Verum and OTLP environment variable templates
- One-line \`import\` added to each file with detected LLM calls

### What this does

A single \`import verum.openai\` (Python) or \`import "@verum/sdk/openai"\` (TypeScript) at the top of your file:
- Patches the OpenAI SDK to route traffic through Verum's A/B engine
- Fails open — if Verum is unreachable, your service continues normally
- Adds 0 tokens to your LLM calls

### Next steps

1. Set \`VERUM_API_URL\`, \`VERUM_API_KEY\`, and \`VERUM_DEPLOYMENT_ID\` in your environment
2. Deploy — Verum starts A/B testing your prompts automatically

> Not affiliated with Verum AI Platform (verumai.com).
`;

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await auth();
  const user = session?.user as Record<string, unknown> | undefined;
  const userId = user?.id as string | undefined;
  if (!userId) return new Response("unauthorized", { status: 401 });
  const rateLimitResponse = await checkRateLimit(userId, 20);
  if (rateLimitResponse) return rateLimitResponse;
  const accessToken = user?.github_access_token as string | undefined;
  if (!accessToken) return new Response("github_access_token missing from session", { status: 401 });

  const { id: repoId } = await params;

  const rawMode = req.nextUrl.searchParams.get("mode") ?? "observe";
  const mode: PrMode = rawMode === "bidirectional" ? "bidirectional" : "observe";

  const repo = await getRepo(userId, repoId);
  if (!repo) return new Response("repo not found", { status: 404 });

  const [analysis, inference] = await Promise.all([
    getLatestAnalysis(repoId),
    getLatestInference(repoId),
  ]);

  if (!analysis) return new Response("no analysis found for this repo", { status: 404 });
  if (analysis.status !== "done") return new Response("analysis not complete yet", { status: 409 });

  // inference is fetched for future use (e.g. domain context in PR body); unused fields are intentionally ignored
  void inference;

  // Fix-C: validate call_sites shape at runtime before use
  const callSitesRaw = CallSitesSchema.safeParse(analysis.call_sites ?? []);
  if (!callSitesRaw.success) {
    return Response.json(
      { error: `call_sites schema invalid: ${callSitesRaw.error.message}` },
      { status: 422 },
    );
  }
  const callSites = callSitesRaw.data;

  // Normalize github_url: strip trailing .git, handle SSH URLs
  const repoFullName = repo.github_url
    .replace(/^git@github\.com:/, "")
    .replace(/^https?:\/\/github\.com\//, "")
    .replace(/\.git$/, "")
    .replace(/\/$/, "");

  const creator = new GitHubPrCreator({ accessToken, repoFullName });

  // Fix-B: wrap file reads in try/catch — readFile re-throws non-404 GitHub errors
  let existingFiles: Record<string, string>;
  try {
    const filesToRead = [
      ".env.example",
      "package.json",
      "requirements.txt",
      ...callSites.map((s) => s.file_path),
    ];
    const entries: Record<string, string> = {};
    await Promise.all(
      filesToRead.map(async (path) => {
        const content = await creator.readFile(path);
        if (content !== null) entries[path] = content;
      }),
    );
    existingFiles = entries;
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    return Response.json({ error: `Failed to read repo files: ${error}` }, { status: 502 });
  }

  const fileChanges = buildPrFileChanges({ callSites, existingFiles, repoFullName, mode });

  if (fileChanges.length === 0) {
    return Response.json(
      { message: "nothing to change — repo already contains Verum configuration" },
      { status: 200 },
    );
  }

  // Fix-B: createSdkPrRequest only after file reads succeed, inside the PR try/catch
  const branchName = `verum/sdk-integration-${Date.now()}`;
  const prTitle =
    mode === "observe"
      ? "Add Verum observability (Phase 0 — env only)"
      : "Add Verum SDK integration (Phase 1 — auto-instrument)";
  const prBody = mode === "observe" ? PR_BODY_OBSERVE : PR_BODY_BIDIRECTIONAL;

  const requestId = await createSdkPrRequest({ userId, repoId, analysisId: analysis.id });

  try {
    const { pr_url, pr_number } = await creator.createPr({
      branchName,
      baseBranch: repo.default_branch,
      title: prTitle,
      body: prBody,
      files: fileChanges,
    });

    await updateSdkPrRequest(requestId, {
      status: "pr_created",
      pr_url,
      pr_number,
      branch_name: branchName,
      files_changed: fileChanges.length,
    });

    return Response.json(
      { request_id: requestId, pr_url, pr_number, files_changed: fileChanges.length },
      { status: 201 },
    );
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e);
    await updateSdkPrRequest(requestId, { status: "error", error });
    return Response.json({ error }, { status: 502 });
  }
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const userId = await getAuthUserId();
  if (!userId) return new Response("unauthorized", { status: 401 });
  const { id: repoId } = await params;
  const request = await getLatestSdkPrRequest(userId, repoId);
  if (!request) return new Response("not found", { status: 404 });
  return Response.json(request);
}
