"""ArcanaInsight tarot reading endpoint — before Verum integration.

This is the original implementation: a static system prompt hardcoded in the
service, calling the LLM provider directly. No observability, no A/B testing,
no automatic improvement.
"""
import os

from openai import OpenAI

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

SYSTEM_PROMPT = """당신은 신비로운 타로 카드 리더입니다.
켈트 십자 스프레드를 사용하여 질문자의 과거, 현재, 미래를 읽어드립니다.
답변은 신비롭고 통찰력 있게, 그러나 따뜻하고 공감적으로 작성하세요."""


def read_tarot(question: str, cards: list[str]) -> str:
    """Generate a tarot reading for the given question and drawn cards.

    Args:
        question: The user's question (in Korean).
        cards: List of tarot card names drawn for this reading.

    Returns:
        The tarot reading text generated by the LLM.
    """
    user_message = f"질문: {question}\n뽑힌 카드: {', '.join(cards)}"

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.8,
    )
    return response.choices[0].message.content or ""


if __name__ == "__main__":
    reading = read_tarot(
        question="올해 제 커리어는 어떻게 될까요?",
        cards=["The Star", "The Hermit", "Wheel of Fortune"],
    )
    print(reading)
